# Generated by Django 3.2.24 on 2024-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Index_No', models.PositiveIntegerField()),
            ],
        ),
    ]
